### ISSUE TITLE
this.array.toPoly is not a function

### ISSUE THREAD

**Issue by sanderginn** [svgdotjs/svg.topoly.js#10]
When I try to run the example, I get the following error logged:

`Uncaught TypeError: this.array.toPoly is not a function
    at initializer.toPoly (svg.topoly.js:164)
    at test.html:22`

**Comment by sanderginn** [comment]
`this.array` seems to have been replaced by `this.array()`, but that leads to:
`Uncaught TypeError: this.parent[type] is not a function
    at initializer.toPoly (svg.topoly.js:149)
    at test.html:22`

**Comment by Fuzzyma** [comment]
The plugin is not up to date with the 2.0 api. We need to fix that first. Thx for the headsup

**Comment by wbern** [comment]
+1

**Comment by Fuzzyma** [comment]
fixed with latest commit. Please report any issues in case I missed something
