### ISSUE TITLE
Missing dist folder on NPM and UNPKG

### ISSUE THREAD

**Issue by cupojoe** [svgdotjs/svg.topoly.js#12]
The package.json points to dist/ folder for unpkg but said folder is missing from the NPM release.

**Comment by Fuzzyma** [comment]
Thats strange. Albeit npm publish ignores files which are in the gitignore, it didnt happen in case of the svg.js repo, the svg.filter.js repo and so on. Why here? I dont get it...

**Comment by Fuzzyma** [comment]
This should be fixed with version 1.0.3
